### PR TITLE
clickable decorator implementation

### PR DESCRIPTION
**Pull request by niklassiemer**

### CODE REVIEW

**Comment by niklassiemer** [comment]
It works, however, I would like to get a better implementation without `inspect.getfullargspec`...

**Review by liamhuber — COMMENTED** [review]
Very nice. One needs a minute to read through the decorator, but the docstring is accurate and the name is good -- the main gui code where it's used is much more readable.

It would be good to add a couple of tests that force the value errors.

**Comment by liamhuber** [comment]
> the main gui code where it's used is much more readable.

Sorry, bad english. Much more readable than it was before when mystery kwargs were being added. Not much more readable than this decorator -- they're both nicely readable. I was trying to talk about dReadability/dt, not dReadability/dFile 😉

**Comment by niklassiemer** [comment]
I allowed for key-word-only `kwargs` in addition and added all the tests 😄

**Pull request merged**
