### PR TITLE
Update dependencies 

### PR DESCRIPTION
**Pull request by jan-janssen**
All in one pull request

### CODE REVIEW

**Comment by jan-janssen** [comment]
Waiting for https://github.com/pyiron/pyiron_atomistics/pull/529

**Comment by jan-janssen** [comment]
Waiting for https://github.com/pyiron/pyiron_base/pull/687

**Comment by jan-janssen** [comment]
```
======================================================================
[1313](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1313)
ERROR: test_activate_gui (project.test_browser.TestActivateGUI)
[1314](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1314)
----------------------------------------------------------------------
[1315](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1315)
Traceback (most recent call last):
[1316](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1316)
  File "/home/runner/work/pyiron_gui/pyiron_gui/tests/project/test_browser.py", line 59, in test_activate_gui
[1317](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1317)
    self.assertTrue(hasattr(gui_pr, attribute),
[1318](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1318)
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/project/generic.py", line 212, in size
[1319](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1319)
    prefix_index = math.floor(math.log2(size) / 10) - 1
[1320](https://github.com/pyiron/pyiron_gui/runs/5112105576?check_suite_focus=true#step:5:1320)
ValueError: math domain error
```

**Comment by jan-janssen** [comment]
@niklassiemer Can you take a look at this? It seems the conversion fails for certain small project sizes.

**Comment by niklassiemer** [comment]
> @niklassiemer Can you take a look at this? It seems the conversion fails for certain small project sizes.

Yes, it fails for size<=0, Fixed in https://github.com/pyiron/pyiron_base/pull/689

**Comment by niklassiemer** [comment]
waiting for next pyiron_base release to include https://github.com/pyiron/pyiron_base/pull/689

**Pull request merged**
